name: Test Python App
on:
  push:
    branches: ['dev']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run Tests
        run: python -m pytest tests/
=======
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install pytest httpx fastapi uvicorn pydantic-settings
    - name: Run Tests
      run: python -m pytest tests/
>>>>>>> dev
